### ISSUE TITLE
Question: Should the lifecycle on the instance itself be set to 'create before destory' to avoid deployment downtime?

### ISSUE THREAD

**Issue by enigmatix** [terraform-aws-modules/terraform-aws-rds-aurora#149]
Hi,

Thanks so much for this module, it's absolutely great :).  I just wanted to verify a concern i had regarding some plan outputs flagging they will destroy my instance.

I can see that because this is an aurora cluster, and that deletion is happening via api, that there shouldn't be any data loss based on the docs posted here:  https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_DeleteInstance.html

However, I am concerned that when i execute this command, that i will briefly not have a RDS instance within the cluster available, which will cause an outage.  Should the lifecycle be set to 'create before destroy' to mitigate this?  

Provided users are referencing cluster endpoints instead of instance endpoints, I'd imagine this should be fine.  Thoughts?

**Comment by antonbabenko** [comment]
Hi @enigmatix !

I guess this can be related to #134 which has been just fixed in [v2.27.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.27.0).

`create_before_destroy` will not help because it will create a new resource with new IDs, so it will be downtime again.

Closing this issue, because I believe #134 covered the case you may have.
