### ISSUE TITLE
v2.29.0 is a breaking change and should be v3.0.0

### ISSUE THREAD

**Issue by mitchellrj** [terraform-aws-modules/terraform-aws-rds-aurora#164]
The changes to resource structure to support optional DB creation require Terraform to remove and replace the database. This breaks existing deployments that may only have their version pinned to "~> 2.x".

**Comment by antonbabenko** [comment]
Hi @mitchellrj !

Looking at changes introduced at #159 I can't see what was actually the breaking change there. All variables seem to have backward compatibility

Can you share the plan or what exactly Terraform was trying to recreate?

**Comment by mitchellrj** [comment]
The variables are the same, but you need to consider the shape of the state file.

A state created with version 2.28.0 has the resource `module.mydb.aws_rds_cluster.this`. Version 2.29.0 doesn't have such a resource, it has `aws_rds_cluster.this[0]`. On update from 2.28 to 2.29 Terrafrom does not magically detect that these are intended to be the same resource, so attempts to delete the first, and create the second. If deletion protection is not enabled, then the DB will be deleted, resulting in an outage and potentially data loss. If deletion protection is enabled, then the upgrade will fail.

If one wanted to upgrade from 2.28 to 2.29 without deleting the DB then a manual transformation of the state file would be required first.

I strongly urge you to recall 2.29.0, test and document upgrade paths, and re-tag it as 3.0.0.

**Comment by antonbabenko** [comment]
Thanks a lot for the answer, I see where the problem is - https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/159/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR36

There are already several users of this module who are using the latest version and went through an upgrade by running `terraform state mv ...` or by recreating it - it is up to users to decide. If I delete the tag or release a fix under v2 it will make problems for those users.

I understand that this may be not an optimal solution for you, but there is not much I can do. Releasing a fix in v2 will break existing behavior for some.

**Comment by mitchellrj** [comment]
Please update the change notes to make it as clear as possible to users what is required to upgrade seemlessly.

Please test for this scenario in future.
