### ISSUE TITLE
work with aws china

### ISSUE THREAD

**Issue by yongzhang** [terraform-aws-modules/terraform-aws-rds-aurora#177]
Hi, 

For:
https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/main.tf#L155
Can you please change this to something like:
`arn:${var.iam_region}:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole`

and set:
```
variable "iam_region" {
  default = "aws"
}
```
so we can set it to `aws-cn` to make it work in AWS China, thanks.

**Comment by yoonix** [comment]
I am running into this issue as well in GovCloud.  

The terraform-aws-modules/rds/aws [solved this same problem with v2.20.0](https://github.com/terraform-aws-modules/terraform-aws-rds/compare/v2.19.0...v2.20.0)

Related issue:
https://github.com/terraform-aws-modules/terraform-aws-rds/issues/229

**Comment by cjpeterein** [comment]
See my comment on 229 https://github.com/terraform-aws-modules/terraform-aws-rds/issues/229#issuecomment-747618005

Instead of passing in a variable for the partition, terraform can look up the current partition directly:

data "aws_partition" "current" {}

Then use ${data.aws_partition.current.partition} instead of the variable.

**Comment by antonbabenko** [comment]
Fixed in #182

Please use [v3.2.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v3.2.0) which has been just released.
