### ISSUE TITLE
create_random_password cant be set as default to true

### ISSUE THREAD

**Issue by eranyo** [terraform-aws-modules/terraform-aws-rds-aurora#185]
On the 20/01 you released new version that its great but you added new option in this version create_random_password that its default is true.
This issue made my team to troubleshoot an issue for 6 hours. 
We set the rds password alone using this module but because this option is set to true by default the module ignored my password and set some random one. 

I think that option like that should be false by default or at lest ignored is i'm setting my our password.

Thanks,
Eran.

**Comment by antonbabenko** [comment]
It is bad that it caused such issues on your side but there was a bug introduced in the previous release where the password was not possible to create conditionally. Issue reported here - #183 

There is no way to identify for sure in Terraform whether a password was provided or not when running this module, so `create_random_password` flag is required is set by default and used.

To prevent such things from happening in the future, always pin the version of Terraform modules you are using.

**Comment by SalimCosmo** [comment]
Hello Anton,

Thanks for your awesome work! It is really helpful for my day to day job. :-)

I ran into the same problem than Eran today, and it took me quite a while to troubleshoot it. However, after more than an hour trying to find an alternative fix that would enable us to enforce the use of our own password even if create_random_password is set to "true" (without creating a random_password ressource because of the existence of my own), I surrendered. As you said, the problem stems from Terraform not knowing whether a password is provided or not, and I couldn't think of a creative way to pass around that.
The thing is, I am wondering if it's not more natural to set create_random_password to false by default. Indeed, when it's true by default, the use of the parameter "password" has no effect, and it is quite difficult to notice this behaviour before a problem happens. On the other hand, if create_random_password is set to false and we don't provide a password, we will automatically get an error when running terraform apply ("The parameter MasterUserPassword must be provided and must not be blank"). We would then put the variable to true, or use our own password, fixing the problem immediately. 

It feels like a more natural design for me. What do you think?

**Comment by denniswebb** [comment]
Why not just a local for `create_random_password = var.password == "" && var.create_random_password ? true : false` or something with better logic if mine is off this morning.

**Comment by SalimCosmo** [comment]
I think that the problem resides on [this line](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/main.tf#L17). We don't want to create a `random_password` resource if we provide our own, but if we use a conditional like `var.password == ""`, Terraform won't be able to evaluate it if `var.password` depends on other resources that cannot be determined until apply (see #183).

**Comment by crosbymichael1** [comment]
I faced the same issues as mentioned above, I think it would be more logical to set random_password to false by default for better backwards compatibility for people upgrading modules.

**Comment by crosbymichael1** [comment]
I have created the below PR which updates the description of password in the readme to inform people that if they are going to provide a password then they need to set the random password generator field to false.

https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/pull/196

**Comment by antonbabenko** [comment]
Fixed in #201
