### ISSUE TITLE
Add Option To Create CNAME R53 Record For Cluster

### ISSUE THREAD

**Issue by toneill818** [terraform-aws-modules/terraform-aws-rds-aurora#247]
## Describe the solution you'd like.
Allow users to pass in a R53 zone id and a DNS name to create a Route 53 Record

## Describe alternatives you've considered.
Can add it outside of the module, but would be nice if this logic was in one place.

**Comment by antonbabenko** [comment]
Hi Thomas,

This kind of feature request is not something we are going to support in this module, because of the nature of the resource modules. RDS Aurora has no relation to Route53 service in order to operate in the first place.

Please use [route53 module](https://github.com/terraform-aws-modules/terraform-aws-route53) to manage records or zones.
