### ISSUE TITLE
create_db_Subnet_Group creates a conflict when leaving out

### ISSUE THREAD

**Issue by RamazanKara** [terraform-aws-modules/terraform-aws-rds-aurora#260]
## Description

When leaving out the create_db_Subnet_group parameter, we would expect the create_db_Subnet_group Parameter to automatically be set to "false" according to the documentation. This is not the case. Instead when we reference a Subnet Group, but leave out the create_db_Subnet_group Parameter we get following error:

│ Error: Error creating DB Subnet Group: InvalidSubnet: Subnet IDs are required.
│ 	status code: 400
│ 
│   with module.keycloak.module.keycloak_database.aws_db_subnet_group.this[0],
│   on .terraform/modules/keycloak.keycloak_database/main.tf line 35, in resource "aws_db_subnet_group" "this":
│   35: resource "aws_db_subnet_group" "this" {

This issue is fixed, when we set the Parameter to false in the module reference. So the default setting of false is here not working correctly.

**Comment by bryantbiggs** [comment]
I'm not sure which documentation you are referring to, but this module defaults to creating the DB subnet group https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/d00931e97350a1e2f04b60328ba10dbbe823e44c/variables.tf#L17 - which is why you need to set it to false to disable the creation
