### ISSUE TITLE
How does terraform state handle a minor version upgrade when auto_minor_version_upgrade is set to true?

### ISSUE THREAD

**Issue by KurtisPyeGMSL** [terraform-aws-modules/terraform-aws-rds-aurora#286]
## Description

A cluster and instance is deployed with `auto_minor_version_upgrade` set to true (which is the default). A new minor version is approved by AWS and the cluster/instance is upgraded during it's next maintenance window. No other changes have taken place. A `terraform apply` is ran - What happens? Does terraform try to change back the cluster/instance version to what it was previously or does it accept the change in version and update it's state? 

## Versions

- Module version: ~>6.1
- Terraform version: v1.1.5
- Provider version(s): AWS provider ~> 3.0

Awaiting a new minor version to be AWS approved to test, but wanted to check this ahead of time. 

## Expected behavior

During a `terraform apply` - Terraform is aware the state says `old_version` but it's check shows the cluster/instance is now upgraded to a `new_version`, therefore terraform thinks a change is required and wants to rollback the update.

## Desired behavior

Terraform may spot a difference of minor version in state vs what is currently deployed, however, it handles this gracefully, updating state to reflect reality and not trying to rollback the cluster/instance. 

## Additional context

Does this module handle this use case in a way that does not result in changes to be applied? If not, is it possible to suggest a flag to set an ignore on `engine_version` to be used in conjunction with `auto_minor_version_upgrade` which may solve this problem?

This issue is intended to be a question or potential request for new behavior.

**Comment by 4wuyan** [comment]
I think https://github.com/hashicorp/terraform-provider-aws/pull/17111 introduced
> resource/aws_rds_cluster_instance: Remove force new resource on the `engine_version` parameter to allow upgrade without remove instances

which is not exactly the same question in this issue.

https://github.com/hashicorp/terraform-provider-aws/pull/20211 seems to achieve the desired behavior for _point_ version upgrade only, e.g. 8.0 -> 8.0.27. Not the _minor_ version upgrade like 13.3 -> 13.4. The current latest definition of [compareActualEngineVersion](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/rds/verify.go) and [its tests](https://github.com/hashicorp/terraform-provider-aws/blob/9b116b188330567c2c77c8fc0f34f366a51412a6/internal/service/rds/engine_version_test.go) seem to confirm that.

I think currently terraform does the expected behavior in the description:
> therefore terraform thinks a change is required and wants to rollback the update.

For an Aurora Postgres auto minor version upgrade from 13.3 to 13.4, terraform will want to revert and hit error. Maybe you have to explicitly add
```terraform
  lifecycle {
    ignore_changes = [
      engine_version
    ]
  }
```

**Comment by james-green-affinity** [comment]
> which is not exactly the same question in this issue.

This is still an issue for me, I have the two values set to:
auto_minor_version_upgrade = true
engine_version          = "8.0.mysql_aurora.3.02.0"

If AWS does a minor DB update, I am then blocked from deploying. Not sure why @bryantbiggs closed this issue without a resolution. 

The problem with adding a 'lifecycle' rule. you will run into issues applying major version upgrades.

**Comment by bryantbiggs** [comment]
perhaps if you read the links provided it would have been more clear.

In short, if you want AWS to manage auto upgrades, then you need to stop restricting parts of the version. You cannot specify a full, complete version AND tell AWS to auto upgrade the minor version, it will conflict with Terraform since the version is changing by AWS.

As you see in the examples we provide, you can relax the version constraints to suite https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/522253054d4bc22d32a54c94b317451f027f03a2/examples/mysql/main.tf#L25

So by setting the following, you should achieve what you are looking for:

```hcl
  auto_minor_version_upgrade = true

  engine         = "aurora-mysql"
  engine_version = "8.0"
```

**Comment by james-green-affinity** [comment]
> perhaps if you read the links provided it would have been more clear.
> 
> In short, if you want AWS to manage auto upgrades, then you need to stop restricting parts of the version. You cannot specify a full, complete version AND tell AWS to auto upgrade the minor version, it will conflict with Terraform since the version is changing by AWS.
> 
> As you see in the examples we provide, you can relax the version constraints to suite
> 
> https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/522253054d4bc22d32a54c94b317451f027f03a2/examples/mysql/main.tf#L25
> 
> So by setting the following, you should achieve what you are looking for:
> 
> ```terraform
>   auto_minor_version_upgrade = true
> 
>   engine         = "aurora-mysql"
>   engine_version = "8.0"
> ```

Thanks I did try this before I posted. but it failed as it was still trying to downgrade the instances. After more reading, I realised I needed a Terraform refresh to make this apply.
