### ISSUE TITLE
RDS InvalidDBInstanceState

### ISSUE THREAD

**Issue by dcGu** [terraform-aws-modules/terraform-aws-rds-aurora#293]
## Description

```
RDS InvalidDBInstanceState: Instance cannot currently reboot due to an in-progress management operation
```

Every time I run `terraform apply`, I run into this issue. The issue seems to be with the reader nodes (https://github.com/hashicorp/terraform-provider-aws/issues/11905) and it was suppose to be fixed but I'm still having the problem

## Versions

- Terraform version: v1.0.7
- Provider version(s): terraform-aws-modules/rds-aurora/aws:5.0

## Reproduction Code [Required]

```bash
terraform apply
```

## Expected behavior

I should be able to run `terraform apply` once and not have it return a 400 Error 

## Actual behavior

I receive a 400 Error

### Terminal Output Screenshot(s)

<img width="1090" alt="400" src="https://user-images.githubusercontent.com/95309316/169405026-638784a6-457f-4baf-a490-7ec2fae0df56.png">

**Comment by bryantbiggs** [comment]
This doesn't look to be a module issue - from the error message, it looks like the AWS RDS service is performing a change on your instance which is preventing you from making subsequent changes at the same time

**Comment by minokyo** [comment]
I met with this issue as well. In particular, I was trying it in ap-east-1 and wonder it's region specific because I've applied the same config on some other regions before and there was no such issue.

I also believe this is AWS provider issue, or at least a AWS regional issue if my finding above is true. So I think the [issue](https://github.com/hashicorp/terraform-provider-aws/issues/11905) may not have completely resolved all scenarios. This is purely guessing....

However, the workaround for me in this case was to run `terraform state rm` before `terraform import` to have terraform "re-manage" the resource. NOTE: The aws_rds_cluster_instance resource was actually successfully created but terraform freaks out because of the AWS API reboot operation.
