### ISSUE TITLE
KMS_KEY_ID recreates database everytime

### ISSUE THREAD

**Issue by sabinayakc** [terraform-aws-modules/terraform-aws-rds-aurora#467]
How do we solve the problem of `kms_key_id` field?

When creating the rds for the first time `kms_key_id = arn`.

<img width="620" alt="image" src="https://github.com/user-attachments/assets/89ad311a-bbe5-4831-8ef2-4b9f104eaf68">

Then running terraform again, `kms_key_id = is not the id` and hence it force replaces. since `arn` is being passed. 

Is there a way we could add a ignore change lifecyle for the `kms_key_id`

I can create a PR if you'd like.

Thank you.

**Comment by skx** [comment]
I guess it would be possible to use a lifecycle hook to ignore changes, but to be honest the issue here is that you're passing a ID not an ARN, so the setting was never valid and in that case ignoring the change seems misguided at best, and pointless at worst.

The preferred solution would be to distroy the instance, and recreate it with a correctly-specified ARN.  Or if your DB is in-use and cannot be replaced then don't update the ARN leaving it without encryption at rest.
