### ISSUE TITLE
[Question][Docs] What are the minimum IAM permissions needed to create an RDS cluster ?

### ISSUE THREAD

**Issue by vishnuhd** [terraform-aws-modules/terraform-aws-rds-aurora#78]
Hi,

Can we please get the minimum IAM permissions needed for an IAM user or IAM role to create an RDS cluster.

This is missing from the README's/Docs, it would be helpful if we can get one.

Thanks.

**Comment by antonbabenko** [comment]
Thank you for opening this issue!

This sounds like a good idea, but realistically it is hard to identify IAM permissions correctly because it depends on what exactly parameters are passed into this module:
* Whether to create Application autoscaling policy?
* Whether to create IAM role for the monitoring?
* Whether to create RDS Aurora Cluster with or without Cluster Instances?
and so on... This module can create all of these and more.

Normally, you should be able to create resources with wide permissions and then scope-down based on what API calls were actually reported into AWS Cloudtrail.

Currently, I don't know about an automated solution which we can use to identify those and include in README.

Please let me know if you know other solution or external tool which we can use for this!

Closing, because I don't think we will be working on this in the near future.
