### ISSUE TITLE
Error deleting security group: DependencyViolation: sg- has a dependent object

### ISSUE THREAD

**Issue by edbighead** [terraform-aws-modules/terraform-aws-rds-aurora#84]
Introduced in [v2.10.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.10.0) by https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/80

`"aws_security_group" "this"`  is being recreated due to `description` change.
```
# module.aurora.aws_security_group.this[0] must be replaced
-/+ resource "aws_security_group" "this" {
      ~ arn                    = "arn:aws:ec2:us-east-1:xxx:security-group/sg-xxx" -> (known after apply)
      ~ description            = "Managed by Terraform" -> "Control traffic to/from RDS Aurora xxx" # forces replacement
      ~ egress                 = [
          - {
              - cidr_blocks      = []
              - description      = ""
              - from_port        = 5432
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
```
**Error:**

```
module.aurora.aws_security_group.this[0]: Still destroying... [id=sg-xxx, 9m20s elapsed]
module.aurora.aws_security_group.this[0]: Still destroying... [id=sg-xxx, 9m30s elapsed]
module.aurora.aws_security_group.this[0]: Still destroying... [id=sg-xxx, 9m40s elapsed]
module.aurora.aws_security_group.this[0]: Still destroying... [id=sg-xxx, 9m50s elapsed]
module.aurora.aws_security_group.this[0]: Still destroying... [id=sg-xxx, 10m0s elapsed]

Error: Error deleting security group: DependencyViolation: resource sg-xxx has a dependent object
	status code: 400, request id: 2e5e5ee3-0a88-459d-a5d6-177979d94bcd
```

**Comment by antonbabenko** [comment]
@miguelaferreira could you please take a look and fix this one?

**Comment by skorfmann** [comment]
we had the same issue.

**Comment by marcincuber** [comment]
Same here.

**Comment by miguelaferreira** [comment]
Hi everyone. Thanks for reporting this.

I'm not sure what the "dependent object" is. In the module the security group is populated with two rules, but since those are under the control of terraform I don't think that's it.

Anyway, for reference, it seems to me like it should be possible to work around this issue by creating a temporary SG to replace the one terraform want's to re-create, then let terraform re-create the SG and assign it back to where it was in the first place. On the other hand, we can also add some code to the module to "fix it". That code would be a new variable to override the description on the SG and set it to the terraform default of "Managed by Terraform". Is that the kind of fix you are looking for @antonbabenko?

**Comment by miguelaferreira** [comment]
I've made a WIP PR #86  to address this issue with a variable to override the SG description. It would be helpful to me if people could test that and validate it is enough to prevent the issue.

**Comment by antonbabenko** [comment]
[v2.12.0](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/releases/v2.11.0) has been released with this bug fixed.

I've based it on #86 but I made this release backward compatible with the previous versions, so it should work without any new arguments (recreation to just update SG is not possible for most users).

**Comment by joaoheron** [comment]
Just had this same issue on Terraform v0.12.29

**Comment by netors** [comment]
I had this issue, turns out that the security group was still attached to an available elastic network interface, navigate to elastic network interfaces and search for your security group there, delete the network interface and terraform will be able to delete it. I got the hint when attempting to manually delete the security group in the AWS Console

**Comment by pritisolanki** [comment]
I added vpc_id and tried applying the change and got this error - Error deleting security group: DependencyViolation: resource sg-xxxx has a dependent object.
